# Generated by Django 6.0.8 on 2026-10-03 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FixtureRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_id", models.CharField(max_length=36, unique=True)),
                ("pool", models.CharField(max_length=12)),
                (
                    "status",
                    models.CharField(
                        choices=[("provisioned", "Provisioned"), ("failed", "Failed")],
                        max_length=11,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["provisioned", "failed"])),
                        name="simulation_fixtures_run_status_valid",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FixtureObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("convention", "Convention"),
                            ("enrollment", "Enrollment"),
                            ("fursuit", "Fursuit"),
                            ("activation", "Activation"),
                        ],
                        max_length=10,
                    ),
                ),
                ("object_id", models.PositiveBigIntegerField()),
                ("media_key", models.TextField(null=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="simulation_fixtures.fixturerun",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kind", "object_id"),
                        name="simulation_fixtures_object_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "kind__in",
                                ["convention", "enrollment", "fursuit", "activation"],
                            )
                        ),
                        name="simulation_fixtures_object_kind_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("kind", "fursuit"), ("media_key__isnull", False)),
                            models.Q(
                                models.Q(("kind", "fursuit"), _negated=True),
                                ("media_key__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="simulation_fixtures_object_media_key_fursuit_only",
                    ),
                ],
            },
        ),
    ]
