# Generated by Django 6.0.8 on 2026-10-04 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("simulation_fixtures", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FixtureIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="FixturePendingImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.TextField(unique=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="fixturerun",
            name="simulation_fixtures_run_status_valid",
        ),
        migrations.AddField(
            model_name="fixturerun",
            name="cleaned_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="fixturerun",
            name="cleanup_counts",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="fixturerun",
            name="reason",
            field=models.CharField(
                choices=[
                    ("journeys", "journeys"),
                    ("reconciliation", "reconciliation"),
                    ("cleanup", "cleanup"),
                    ("interrupted", "interrupted"),
                ],
                max_length=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="fixturerun",
            name="status",
            field=models.CharField(
                choices=[
                    ("provisioned", "Provisioned"),
                    ("failed", "Failed"),
                    ("retained", "Retained"),
                    ("cleaned", "Cleaned"),
                ],
                max_length=11,
            ),
        ),
        migrations.AddConstraint(
            model_name="fixturerun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["provisioned", "failed", "retained", "cleaned"])
                ),
                name="simulation_fixtures_run_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="fixturerun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("reason__isnull", True),
                    (
                        "reason__in",
                        ["journeys", "reconciliation", "cleanup", "interrupted"],
                    ),
                    _connector="OR",
                ),
                name="simulation_fixtures_run_reason_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="fixturerun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "retained"), _negated=True),
                    ("reason__isnull", False),
                    _connector="OR",
                ),
                name="simulation_fixtures_run_retained_has_reason",
            ),
        ),
        migrations.AddConstraint(
            model_name="fixturerun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("cleaned_at__isnull", False), ("status", "cleaned")),
                    models.Q(
                        models.Q(("status", "cleaned"), _negated=True),
                        ("cleaned_at__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="simulation_fixtures_run_cleaned_at_iff_cleaned",
            ),
        ),
        migrations.AddField(
            model_name="fixtureidentity",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="simulation_fixtures.fixturerun",
            ),
        ),
        migrations.AddField(
            model_name="fixturependingimage",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="simulation_fixtures.fixturerun",
            ),
        ),
        migrations.AddConstraint(
            model_name="fixtureidentity",
            constraint=models.UniqueConstraint(
                fields=("run", "index"), name="simulation_fixtures_identity_unique"
            ),
        ),
    ]
