# Generated by Django 6.0.8 on 2026-09-21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="accounts_user_local_password_requires_admin",
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_staff", True),
                    ("password__startswith", "!"),
                    _connector="OR",
                ),
                name="accounts_user_local_password_requires_staff",
            ),
        ),
    ]
