# Generated by Django 6.0.8 on 2026-09-22 02:44

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OperatorAuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("remove_catch", "Remove catch"),
                            ("revoke_catch_credential", "Revoke catch credential"),
                            ("terminate_catch_session", "Terminate catch session"),
                            (
                                "deactivate_fursuit_activation",
                                "Deactivate fursuit activation",
                            ),
                            (
                                "remove_convention_enrollment",
                                "Remove convention enrollment",
                            ),
                            ("set_profile_enabled", "Set profile enabled"),
                            ("set_fursuit_enabled", "Set fursuit enabled"),
                            (
                                "set_convention_playability",
                                "Set convention playability",
                            ),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "actor_class",
                    models.CharField(
                        choices=[
                            ("operator", "Operator"),
                            ("emergency_superuser", "Emergency superuser"),
                            ("unauthorized_actor", "Unauthorized actor"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "affected_record_type",
                    models.CharField(
                        choices=[
                            ("catches.catch", "Catch"),
                            (
                                "conventions.fursuitcatchcredential",
                                "Fursuit catch credential",
                            ),
                            (
                                "conventions.fursuitcatchsession",
                                "Fursuit catch session",
                            ),
                            ("conventions.fursuitactivation", "Fursuit activation"),
                            (
                                "conventions.conventionenrollment",
                                "Convention enrollment",
                            ),
                            ("profiles.playerprofile", "Player profile"),
                            ("fursuits.fursuit", "Fursuit"),
                            ("conventions.convention", "Convention"),
                        ],
                        max_length=64,
                    ),
                ),
                ("affected_record_id", models.PositiveBigIntegerField()),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("succeeded", "Succeeded"),
                            ("denied", "Denied"),
                            ("rejected", "Rejected"),
                            ("failed", "Failed"),
                        ],
                        max_length=16,
                    ),
                ),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("actor_class", "unauthorized_actor"),
                                ("outcome", "denied"),
                            ),
                            models.Q(
                                (
                                    "actor_class__in",
                                    ("operator", "emergency_superuser"),
                                ),
                                models.Q(("outcome", "denied"), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="operator_audit_actor_outcome_valid",
                    )
                ],
            },
        ),
    ]
