# Generated by Django 6.0.8 on 2026-09-17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [
        ("accounts", "0001_initial"),
        ("conventions", "0005_fursuitcatchcredential"),
        ("fursuits", "0002_fursuit_tailtag_id"),
    ]
    operations = [
        migrations.CreateModel(
            name="StagingResetIdentity",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(primary_key=True, serialize=False),
                ),
                ("environment_id", models.UUIDField()),
                ("cluster_identifier", models.CharField(max_length=32)),
                ("database_name", models.CharField(max_length=63)),
                ("media_key", models.TextField()),
                (
                    "catcher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "convention",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="conventions.convention",
                    ),
                ),
                (
                    "first_fursuit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="fursuits.fursuit",
                    ),
                ),
                (
                    "second_fursuit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="fursuits.fursuit",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("id", 1)),
                        name="rehearsal_reset_identity_singleton",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("convention__isnull", True),
                                ("first_fursuit__isnull", True),
                                ("second_fursuit__isnull", True),
                            ),
                            models.Q(
                                ("convention__isnull", False),
                                ("first_fursuit__isnull", False),
                                ("second_fursuit__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="rehearsal_reset_identity_roots_complete",
                    ),
                ]
            },
        )
    ]
