# Generated by Django 6.0.8 on 2026-09-09 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("fursuits", "0002_fursuit_tailtag_id"),
        ("conventions", "0005_fursuitcatchcredential"),
    ]

    operations = [
        migrations.CreateModel(
            name="Catch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caught_at", models.DateTimeField(auto_now_add=True)),
                (
                    "activation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="catches",
                        to="conventions.fursuitactivation",
                    ),
                ),
                (
                    "catch_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="catches",
                        to="conventions.fursuitcatchsession",
                    ),
                ),
                (
                    "catcher_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="catches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "convention",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="catches",
                        to="conventions.convention",
                    ),
                ),
                (
                    "fursuit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="catches",
                        to="fursuits.fursuit",
                    ),
                ),
            ],
            options={
                "ordering": ["-caught_at", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("catcher_user", "fursuit", "convention"),
                        name="catches_catcher_fursuit_convention_unique",
                    )
                ],
            },
        ),
    ]
