analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
include: package:flutter_lints/flutter.yaml
linter:
  rules:
    # prefer_double_quotes: true
    # prefer_single_quotes: true
    # always_specify_types: true

