# Generated by Django 6.0.8 on 2026-08-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Convention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The official name of the convention.", max_length=255
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="Operational lifecycle state of the convention.",
                        max_length=32,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(help_text="Start date of the convention."),
                ),
                ("end_date", models.DateField(help_text="End date of the convention.")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-start_date", "name"],
                "indexes": [
                    models.Index(
                        fields=["status", "start_date", "end_date"],
                        name="conventions_status_dates_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("name", ""), _negated=True),
                        name="conventions_convention_name_not_empty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                [
                                    "draft",
                                    "active",
                                    "paused",
                                    "completed",
                                    "cancelled",
                                ],
                            )
                        ),
                        name="conventions_convention_status_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("end_date__gte", models.F("start_date"))),
                        name="conventions_convention_end_date_gte_start_date",
                    ),
                ],
            },
        ),
    ]
