# Generated by Django 6.0.8 on 2026-09-01 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conventions", "0002_conventionenrollment"),
        ("fursuits", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FursuitActivation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField()),
                ("activated_at", models.DateTimeField()),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "convention",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fursuit_activations",
                        to="conventions.convention",
                    ),
                ),
                (
                    "fursuit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="convention_activations",
                        to="fursuits.fursuit",
                    ),
                ),
            ],
            options={
                "ordering": ["fursuit_id", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("fursuit", "convention"),
                        name="conventions_activation_fursuit_convention_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("deactivated_at__isnull", True), ("is_active", True)
                            ),
                            models.Q(
                                ("deactivated_at__isnull", False), ("is_active", False)
                            ),
                            _connector="OR",
                        ),
                        name="conventions_activation_state_timestamps_valid",
                    ),
                ],
            },
        ),
    ]
