# Generated by Django 6.0.8 on 2026-09-01 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conventions", "0003_fursuitactivation"),
    ]

    operations = [
        migrations.CreateModel(
            name="FursuitCatchSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "end_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("owner", "Owner"),
                            ("operator", "Operator"),
                            ("eligibility_lost", "Eligibility lost"),
                            ("expired", "Expired"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "activation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="catch_sessions",
                        to="conventions.fursuitactivation",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at", "-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("expires_at__gt", models.F("started_at"))),
                        name="conventions_catch_session_expiry_after_start",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("end_reason__isnull", True), ("ended_at__isnull", True)
                            ),
                            models.Q(
                                ("end_reason__isnull", False),
                                ("ended_at__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="conventions_catch_session_end_fields_paired",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("ended_at__isnull", True),
                            ("ended_at__gte", models.F("started_at")),
                            _connector="OR",
                        ),
                        name="conventions_catch_session_end_not_before_start",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("end_reason__isnull", True),
                            (
                                "end_reason__in",
                                ["owner", "operator", "eligibility_lost", "expired"],
                            ),
                            _connector="OR",
                        ),
                        name="conventions_catch_session_end_reason_valid",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("ended_at__isnull", True)),
                        fields=("activation",),
                        name="conventions_catch_session_one_unended_per_activation",
                    ),
                ],
            },
        ),
    ]
