# Generated by Django 6.0.8 on 2026-09-01 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conventions", "0004_fursuitcatchsession"),
        ("fursuits", "0002_fursuit_tailtag_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="FursuitCatchCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=43)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "revocation_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("owner_rotation", "Owner rotation"),
                            ("operator", "Operator"),
                            ("eligibility_lost", "Eligibility lost"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "activation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="catch_credentials",
                        to="conventions.fursuitactivation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("revocation_reason__isnull", True),
                                ("revoked_at__isnull", True),
                            ),
                            models.Q(
                                ("revocation_reason__isnull", False),
                                ("revoked_at__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="conventions_catch_credential_revocation_fields_paired",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("revocation_reason__isnull", True),
                            (
                                "revocation_reason__in",
                                ["owner_rotation", "operator", "eligibility_lost"],
                            ),
                            _connector="OR",
                        ),
                        name="conventions_catch_credential_revocation_reason_valid",
                    ),
                    models.UniqueConstraint(
                        fields=("token",),
                        name="conventions_catch_credential_token_unique",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("revoked_at__isnull", True)),
                        fields=("activation",),
                        name="conventions_catch_credential_one_current_per_activation",
                    ),
                ],
            },
        ),
    ]
