# Generated by Django 6.0.8 on 2026-08-24 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="player_profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("handle", models.CharField(max_length=32, null=True)),
                ("display_name", models.CharField(max_length=50, null=True)),
                ("avatar_key", models.TextField(null=True)),
                ("onboarding_completed_at", models.DateTimeField(null=True)),
                ("is_enabled", models.BooleanField(default=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("handle",), name="profiles_player_profile_handle_unique"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("handle__isnull", True),
                            ("handle__regex", "^[a-z0-9][a-z0-9_]{1,31}$"),
                            _connector="OR",
                        ),
                        name="profiles_player_profile_handle_format",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("display_name__isnull", True),
                                ("handle__isnull", True),
                                ("onboarding_completed_at__isnull", True),
                            ),
                            models.Q(
                                ("display_name__isnull", False),
                                ("handle__isnull", False),
                                ("onboarding_completed_at__isnull", False),
                                models.Q(("display_name", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="profiles_player_profile_onboarding_state_consistent",
                    ),
                ],
            },
        ),
    ]
