# Generated by Django 6.0.8 on 2026-09-22 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerprofile',
            options={'permissions': [('set_profile_enabled', 'Can set player profile enabled state')]},
        ),
    ]
