# Generated by Django 6.0.8 on 2026-09-22 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fursuits', '0002_fursuit_tailtag_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fursuit',
            options={'ordering': ['id'], 'permissions': [('set_fursuit_enabled', 'Can set fursuit enabled state')]},
        ),
    ]
