# Generated by Django 6.0.8 on 2026-10-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PoolSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pool", models.CharField(max_length=12)),
                ("index", models.PositiveIntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("quarantined", "Quarantined"),
                        ],
                        default="available",
                        max_length=11,
                    ),
                ),
                ("run_id", models.CharField(blank=True, max_length=36, null=True)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("pool", "index"), name="simulation_pool_slot_unique"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("state__in", ["available", "quarantined"])),
                        name="simulation_pool_slot_state_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("lease_expires_at__isnull", True),
                                ("run_id__isnull", True),
                            ),
                            models.Q(
                                ("lease_expires_at__isnull", False),
                                ("run_id__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="simulation_pool_slot_lease_complete",
                    ),
                ],
            },
        ),
    ]
